

services:
  vehicles-brand:
    container_name: vehicles-brand
    restart: always
    image: node:20.10.0
    ports:
      - 4000:3000
    environment:
      - PORT=3000

    volumes:
      - ./:/usr/src/vehicles-brand
    working_dir: /usr/src/vehicles-brand
    networks:
      - client-network

    # FOR PRODUCTION
    command: bash -c "yarn && yarn run build && yarn run start"

networks:
  client-network:
    driver: bridge
# vehicles-next localhost:4000 => container:3000
# vehicles-api localhost:4001 => container:3007
# vehicles-batch localhost:4002 => container:3008
